name: todo_nti5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  dio: ^5.9.2
  dartz: ^0.10.1
  shared_preferences:
  go_router: ^17.0.0
  image_picker: ^1.2.1
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
  fonts:
     - family: LexendDeca
       fonts:
         - asset: assets/fonts/LexendDeca-VariableFont_wght.ttf